home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('', views.index , name = 'home'),
    path('postAns/<int:queId>', views.postAns, name='postAns'),
    path('askQues/', views.askQues, name='askQues'),
    path('like/', views.like_answer ,name="like-asnwer"),
]

quora/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.loginCustomer, name="loginCustomer"),
# user/password = testing/temporary123
    path('logout/',views.logoutCustomer,name="logoutCustomer"),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):
    qid = models.AutoField(primary_key=True)
    uname = models.CharField(max_length=50)
    que = models.CharField(max_length=200)
    date = models.DateField()
    
    def __str__(self):
        return self.que


class Answer(models.Model):
    aid = models.AutoField(primary_key=True, default=False)
    queid = models.ForeignKey(Question, related_name="answr", on_delete=models.CASCADE)
    uname = models.CharField(max_length=50)
    ans = models.TextField()
    liked = models.ManyToManyField(User, related_name="liked", default=None, blank=True)
    date = models.DateField()


#Using 'property' decorator to 'count_likes()' method
    @property
    def count_likes(self):
        return self.liked.all().count()
    
    def __str__(self):
        return self.ans

LIKE_CHOICES = (('Like','Like'),('Unlike','Unlike'))

class Like(models.Model):
    uname = models.ForeignKey(User, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default='Like',max_length=10)

    def __str__(self):
        return str(self.answer)

users/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms

class questions(forms.Form):
    question = forms.CharField(label="Question", widget=forms.TextInput(attrs={'class':'form-control', 'style':'border:1px solid black'}), max_length=200)
#    que1 = forms.CharField(widget=forms.TextInput)

class answers(forms.Form):
    answer = forms.CharField(label= "Answer", widget=forms.Textarea(attrs={'class':'form-control', 'style':'border:1px solid black'}))

home/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from .forms import questions, answers
from datetime import datetime
from home.models import Question, Answer, Like
from django.contrib import messages

# Create your views here.
def index(request):
    que_set = Question.objects.all()
    name = request.user
    data={"ques":que_set, "name":name}
    try:
        return render(request, 'index.html',data)
    
    except:
        pass


def postAns(request, queId):
    a=answers()
    query_set = Question.objects.get(qid=queId)
    data={"aForm":a, 'ques':query_set}
    try:
        if request.method == 'POST': 
            if request.user.is_authenticated:
                ans = request.POST.get('answer')
                uname = request.user.username
                answer = Answer(ans=ans, queid=query_set, like=0, uname=uname, date=datetime.today())
                answer.save()
                messages.success(request, "Answer Posted Successfully!")
                return redirect("/")
            else:
                messages.warning(request, "You are not Logged in")
                

        return render(request, 'postAns.html',data)
    except Exception as e:
        print(e)
        


def askQues(request):
    q=questions()
    query_set = Question.objects.all()
    query_set= reversed(query_set)
    data={"qForm":q, 'ques':query_set}
    try:
        if request.method == 'POST':
            if request.user.is_authenticated:
                form = questions(request.POST)
                if form.is_valid():
                    que = request.POST['question']
                    uname = request.user.username
                    question = Question(uname=uname, que=que, date=datetime.today())
                    question.save()
                    messages.success(request, "Question Submitted Successfully!")
                return HttpResponseRedirect('/askQues', data)
            else:
                messages.warning(request, "You are not Logged in")

        return render(request, 'askQues.html',data)
    except:
        pass


def like_answer(request):
    uname = request.user
    if request.method == "POST":
        answer_id = request.POST.get('answer_id')
        answer_obj = Answer.objects.get(aid=answer_id)
        
        if uname in answer_obj.liked.all():
            answer_obj.liked.remove(uname)
        else:
            answer_obj.liked.add(uname)

        like, created = Like.objects.get_or_create(uname=uname, answer_id=answer_id)
        if not created:
            if like.value =='Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        like.save()
    return redirect('/')

users/views.py
from django.shortcuts import render,HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.models import User

# Create your views here.

def register(request):

    try:
        if request.method == 'POST':
            uname = request.POST.get('uname')
            email = request.POST['email']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            if (password1 == password2):
                if (not User.objects.filter(username=uname).exists()):
                    if (not User.objects.filter(email=email).exists()):
                        user = User.objects.create_user(username=uname, password=password1, email=email)
                        user.save()
                        messages.success(request,'You Are Registered Successfully!')
                        return redirect('/users/login')
                    else:
                        messages.info(request, 'Email Already registered')
                        return render(request, 'register.html')
                else:
                    messages.info(request, 'Username Already Exist')
                    return render(request, 'register.html')
            else:
                messages.info(request, 'Password Mismatch')
                return render(request, 'register.html')
        else:
            return render(request, 'register.html')
    except:
        pass 



def loginCustomer(request):
    try:
        if request.method=="POST":
            username = request.POST['Username']
            Pass = request.POST.get('Password')
            user = authenticate(username=username, password=Pass)
            if user is not None:
                login(request, user)
                messages.info(request,f"Welcome {username}! ")
                return redirect("/")

            else:
                messages.error(request,"Invalid username or password.")
                return render(request,'login.html')

        return render(request,'login.html')
    except:
        pass


def logoutCustomer(request):
    try:
        if request.user.is_anonymous:
            return redirect("/users/login")
        else:
            logout(request)
            messages.success(request,"Logged Out Successfully!")
        return redirect("/users/login")
    except:
        pass

templates/askQues.html
{% extends 'base.html' %}

{% block title %}
Ask Ques
{% endblock title %}

{% block content %}


<div class="container d-flex py-4" style="justify-content:center">
    
    <div class="row">
        <h1> Please ask your question here </h1>
        <form method="post" action="/askQues/">
            {% csrf_token %}
            {{qForm}}
            <div class="py-2">
                <button class="btn btn-primary " type="submit"> Submit</button> 
            </div>
        </form>
</div>
</div>

<div class="container d-flex py-4" style="justify-content:center">
    
    <div class="row">
        <h1> Please answer if you know any of the question </h1>
        {% for q in ques %}
        <div class ="row">
            <h3> Q: <a href="{% url 'home:postAns' q.qid %}" >{{q.que}} </a> </h3>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/base.css"> 
    
  </head>    
  <body>
    <div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark-red " style="background-color:red">
        <div class="container-fluid">
          <a class="navbar-brand" href="/" style="color:white"><b>Quora</b></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link " aria-current="page" href="/" style="color:white">Home</a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="/askQues" style="color:white">Ask Questions</a>
            </li>
            </ul>

            {% if request.user.is_authenticated %}
            {% with x="Logout" %}
            <div>
            <a class="nav-link" href="/users/logout" >
                <button class="btn btn-outline-success" style="position: relative; right:10px; background-color: #4CAF50; color:white"  type="submit"> {{x}}</button>
                </a>
            </div>
            {% endwith %}
            {% else %}
            {% with x="Login" %}
            <div>
            <a class="nav-link" href="/users/login" >
                <button class="btn btn-outline-success" style="position: relative;  right:10px; background-color: #4CAF50; color:white" type="submit"> {{x}}</button>
                </a>
            </div>
            {% endwith %}
            {% endif %}

            </form>
          </div>
        </div>
      </nav>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show my-0" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

    {% block content %}
    {% endblock content %}

    <title>
    {% block title %}
    {% endblock title %}
    </title>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Quora
{% endblock title %}

{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="container d-flex py-4" style="justify-content:center">

    <div class="row">
        {% if request.user.is_authenticated %}
        <h1 class="pb-3" style="text-align:center"> Welcome to the <span style="color:red; font-weight:bold">Quora </span> Feed <u> {{name}} </u> </h1>
        {% else %}
        <h1 class="pb-3"  style="text-align:center"> Welcome to the <span style="color:red; font-weight:bold">Quora </span> Feed  </h1>
        {% endif %}
        {% for q in ques %}
        {% if q.answr.all %}
        <div class="card my-2">
        <div class="card-header bg-transparent border-success">
            <div class="row">
                <div class="col-md-4"> Asked by: {{q.uname}} </div>
                <div class="col-md-4 offset-md-4 "  style="text-align:right"> Date: {{q.date}} </div>
            </div>
            <div class="row">
                <h3> Q: <a href="{% url 'home:postAns' q.qid %}" style="text-decoration: none; ">{{q.que}} </a> </h3>
            </div>
        </div>    
        
            {% for a in q.answr.all %}
            <div class="card-body text-success">
            <div class ="row">
                <h6><b> Answer {{forloop.counter}}: </b> {{a.ans}}</h6>
            </div>
        </div>
            <div class="row mb-3 ">
                <div class="col-md-4"> Answered by: {{a.uname}} </div>
                
                <div class="col-md-4" style="text-align:center">

                    {% if request.user.is_anonymous %}
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal1">
                        <i class="fa fa-thumbs-up"> </i> <span class="icon"> Like {{ a.liked.all.count }} </span></button>

                    <!-- Button trigger modal -->
                    <!-- popup Modal -->
                    <div class="modal fade" id="exampleModal1" tabindex="-1" aria-labelledby= "exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Please Login</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Login before Liking any Answer.
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary" onclick="window.location.href='/users/login'" >Login</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <form action="{% url 'home:like-asnwer' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden",id="answer_id", name="answer_id", value="{{a.aid}}">
                        {% if name not in a.liked.all %}
                            <button type="submit" class="btn btn-secondary" id="like" value="{{a.aid}}">
                                <i class="fa fa-thumbs-up"> </i>  </button>
                                <span > {{ a.liked.all.count }} Likes  </span>
                        {% else %}
                            <button type="submit" class="btn btn-success" id="like" value="{{a.aid}}">
                                <i class="fa fa-thumbs-up"> </i></button>
                                <span > {{ a.liked.all.count }} Likes  </span>
                        {% endif %}

                        </form>
                    {% endif %}
                </div>

                <div class="col-md-4 offset"  style="text-align:right"> Date: {{a.date}} </div>
            </div>
            
            {% endfor %}
        </div>  

            {% endif %}

            {% endfor %}
    </div>

</div>
{% endblock content %}



templates/login.html
{% extends 'base.html' %}
{% block title %}
  Login
{% endblock %}

{% block content %}
<div class="container my-4" style="text-align:center">
  <div class="card border-success mb-3 mx-auto align-items-center" style="max-width: 25rem;">
    <form method="POST" action="/users/login/">
      {% csrf_token %}
      <div class="card-header bg-transparent border-success">
        <h2>Login to your account</h2>
      </div>
      <div class="card-body text-success">
        <div class="py-2">
          <input class="py-1" style="text-align:center" type="text" name="Username" placeholder="Username" required />
        </div>
        <div class="py-2">
          <input class="py-1" style="text-align:center" type="password" name="Password" placeholder="Password" required />
        </div>

        <button type="submit" class="btn btn-primary mt-2">Login</button>
      </div>
    </form>

    <div class="card-footer bg-transparent border-success">
      <div class="d-flex justify-content-center links">
        Don't have an account? <a class="underlineHover" href="/users/register">Sign Up</a>
      </div>
      <div>
        <a class="forgot" href="#">Forgot Username?</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logged Out</title>
</head>
<body>
<p> You have logged out successfully.</p>
<a href="/login"> Login again </a>
</body>
</html>

templates/postAns.html
{% extends 'base.html' %}

{% block title %}
Post Answers
{% endblock title %}

{% block content %}

<div class="container d-flex py-4" style="justify-content:center">
    
    <div class="row">
        <h1> {{ques.que}} </h1>

        <div class ="row">
        <form method="POST" action="/postAns/{{ques.qid}}">
            {% csrf_token %}
            {{aForm}}
            <div class="py-2">
                <button class="btn btn-primary " type="submit"> Post</button> 
            </div>
        </form> 
    </div>
</div>
</div>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
<section class=" bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form method="post", action=''>
                {% csrf_token %}


                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Username</label>
                  <input type="text" name='uname' id="form3Example3cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example3cg">Your Email</label>
                  <input type="email" name='email' id="form3Example3cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example4cg">Password</label>
                  <input type="password" name='password1' id="form3Example4cg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-outline mb-2">
                    <label class="form-label" for="form3Example4cdg">Repeat your password</label>
                  <input type="password" name='password2' id="form3Example4cdg" class="form-control form-control-lg" required/>
                </div>

                <div class="form-check d-flex justify-content-center mb-3">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg" required/>
                  <label class="form-check-label" for="form2Example3g">
                    I agree all statements in <a href="#!" class="text-body"><u>Terms of service</u></a>
                  </label>
                </div>

                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Register</button>
                </div>

                <p class="text-center text-muted mt-3 mb-0">Have already an account? <a href="/users/login"
                    class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock content %}

{% block title %}
Registration Form
{% endblock title %}